DIR_INC = ./include
DIR_SRC = ./src
DIR_OBJ = ./output
DIR_BIN = ./output

SRC = $(wildcard ${DIR_SRC}/*.cpp)  
OBJ = $(patsubst %.cpp,${DIR_OBJ}/%.o,$(notdir ${SRC})) 
TARGET = thingLink
BIN_TARGET = ${DIR_BIN}/${TARGET}

CC = g++
CXXFLAGS = -Wall -I$(DIR_INC) -O2 -std=c++11
LDFLAGS = -pthread -lreactcpp -lev -Wl,--no-as-needed

${BIN_TARGET}:${OBJ}
	$(CC) $(OBJ)  -o $@ $(LDFLAGS)

${DIR_OBJ}/%.o:${DIR_SRC}/%.cpp
	$(CC) $(CXXFLAGS) -c  $< -o $@

.PHONY:clean
clean:
	find ${DIR_OBJ} -name *.o -exec rm -rf {} \;
